2 plano de riscos
UnBArqDsw2021-1/2021.1_G01_Animalesco_docs pull request #25
Opened 2021-07-29 01:10 UTC by KiSobral

Este pull request engloba a criação do documento de gerenciamento de riscos do projeto.

2021-07-29 02:18 UTC, LeoSilvaGomes requested changes
O documento ficou muito bom, muito bem explicado! 🎉 
Consegui encontrar apenas uma falha na elaboração da prioridade de um dos riscos. Além disso eu acho que esse MR só deve entrar na main do projeto após a mudança do docs de mkdocs para docsify, tendo em vista que essa é uma mudança estrutural no projeto e será melhor implementada sem nenhum documento presente! 😞

2021-07-29 02:18 UTC, LeoSilvaGomes commented on pages/plano-de-riscos.md
> +| RSGP01 | Comunicação ineficiente entre os membros da equipe | Falta de alinhamento entre o time de desenvolvimento | Médio | Média | Média |
A prioridade nesse risco deveria ser `baixa` de acordo com a tabela produzida pela dupla

2021-07-30 01:02 UTC, KiSobral commented on pages/plano-de-riscos.md
> +| RSGP01 | Comunicação ineficiente entre os membros da equipe | Falta de alinhamento entre o time de desenvolvimento | Médio | Média | Média |
Resolvido :wink:

2021-07-30 11:55 UTC, durvalcarvalho approved these changes
O documento ficou ótimo! Gostei muito dos riscos que você identificou.

Peço para que corriga os conflitos e realize o merge com a `main` o mais rápido possível, para facilitar a integração das demais branches.

2021-07-30 14:44 UTC, merged