WiP - Baseline de Requisitos
UnBArqDsw2021-1/2021.1_G01_Animalesco_docs pull request #54
Opened 2021-08-04 19:02 UTC by Rafaelltm

Co-authored-by: JoaoVitorFarias <jvlopesfarias@gmail.com>

2021-08-05 20:37 UTC, KiSobral requested changes
É necessário realizar as trocas requisitadas

2021-08-05 20:37 UTC, KiSobral commented on docs/pages/Baseline_Requisitos.md
> +|FT01| Cadastro de usuário |EP01|
As FT01 e FT02 podem ser resumidas em uma só feature de usuário

2021-08-05 20:37 UTC, KiSobral commented on docs/pages/Baseline_Requisitos.md
> +|FT03| Cadastro de pet |EP02|
Ter uma feature apenas com 'pets'

2021-08-05 20:37 UTC, KiSobral commented on docs/pages/Baseline_Requisitos.md
> +| EP03 | Acompanhamento de idas ao veterinário|
Um melhor nome para este épico seria Acompanhamento de eventos do pet

2021-08-05 20:37 UTC, KiSobral commented on docs/pages/Baseline_Requisitos.md
> +|FT07| Controle de medidas |EP03|
Relacionar com o épico de pet

2021-08-05 20:37 UTC, KiSobral commented on docs/pages/Baseline_Requisitos.md
> +|FT06| Controle de vacinas|EP02|
Relacionar com o épico de eventos

2021-08-05 20:37 UTC, KiSobral commented on docs/pages/Baseline_Requisitos.md
> +|ID | História de usuário | ID Feature |
É necessário atualizar as histórias de usuário a partir das novas definições exigidas na revisão.

2021-08-05 20:37 UTC, KiSobral commented on docs/pages/Baseline_Requisitos.md
> +|US28|Eu como __usuário__ desejo __visualizar__ um relátorio sobre a saúde do pet para ter acesso fácil a isso.|FT08|
Adicionar referencial bibliográfico

2021-08-06 00:48 UTC, KiSobral approved these changes

2021-08-06 01:03 UTC, LeoSilvaGomes requested changes
Ta muito bom 🎉 Parabéns aos envolvidos

2021-08-06 01:04 UTC, LeoSilvaGomes commented on docs/_sidebar.md
> +- **Modelagem**
A modelagem deve vir após a elicitação

2021-08-06 01:22 UTC, LeoSilvaGomes approved these changes
Bem bom gente 🎉  ❤️ Congras

2021-08-06 01:22 UTC, merged