#65 Package diagram
UnBArqDsw2021-1/2021.1_G01_Animalesco_docs pull request #77
Opened 2021-08-15 22:11 UTC by viniciusoliveira96

#65 Issue Package diagram

2021-08-16 20:11 UTC, KiSobral requested changes
É necessário apenas fazer algumas modificações eventuais no diagrama.

2021-08-16 20:11 UTC, KiSobral commented on docs/pages/diagrama-de-pacotes.md
> +    <img src='https://raw.githubusercontent.com/UnBArqDsw2021-1/2021.1_G01_Animalesco_docs/main/docs/assets/pages/diagrama-pacote/diagrama-pacote.png'>
É preciso ajeitar o diagrama de pacotes para que este apresente um melhor detalhamento acerca da estrutura do software. Isto é, incluir no diagrama de pacotes do backend:
- o arquivo de rotas
- o arquivo index.js e como este se relaciona com outras camadas da aplicação
- qual o módulo que o banco de dados se relaciona 
- as relações de dependência entre models, controllers e services.

É necessário repetir o mesmo para o diagrama do frontend, isto é, melhor explicitar as relações entre os módulos internos do próprio pacote.

2021-08-17 00:57 UTC, viniciusoliveira96 commented
Adicionados ajustes solicitados no diagrama

2021-08-17 02:31 UTC, KiSobral approved these changes
:partying_face: :partying_face: :partying_face:

2021-08-17 02:32 UTC, merged